### ISSUE TITLE
Update to v2.2.0 and use new upcoming filter

### ISSUE THREAD

**Issue by JRascagneres** [ludeeus/pylaunches#9]
I filed an associated issue over on Home Assistant repo - https://github.com/home-assistant/core/issues/91487

Would be great if we could update to 2.2.0 as this is the latest LL2 API version and also use the `hide_recent_previous=True` filter for upcoming launches.

Let me know if you have any questions. I'm an LL2 dev.

**Comment by ludeeus** [comment]
Thanks for notifying me 👍
